### ISSUE TITLE
Fix the Travis CI when moving to 8/04

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/TodoList-MongoDB#2]
6/20 supported driver for MongoKitten is broken. We will just skip this release and when Kitura supports 8/04- move to that.

**Comment by Joannis** [comment]
@rfdickerson what's broken about MongoKitten in 6/20? I could make a patch for you guys temporarily.

**Comment by rfdickerson** [comment]
I'm closing this issue since we updated to Swift 3.0.
