### ISSUE TITLE
Build error on Mac OS

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/TodoList-MongoDB#4]
6/8 of the test cases pass.

**Comment by rfdickerson** [comment]
@jesspittman Do we only get this Mac testing error when it runs on Travis? Do we get it when running the tests locally?

https://travis-ci.org/IBM-Swift/TodoList-MongoDB/jobs/161736170

**Comment by rfdickerson** [comment]
Can we close this ticket, @jesspittman ?

**Comment by jesspittman** [comment]
Yeah, it built fine the last couple of times i tried it.
